files:
  - /var/log/taimurain_uwsgi.log
  - /var/log/nginx/suripu-taimurain-access.log
destination:
  host: logs2.papertrailapp.com
  port: 11366   # NOTE: change to your Papertrail port
  protocol: tls
