metrics_enabled : false
debug: true

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

common_db:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: your postgresql username

  # the password
  password: your postgresql password

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/[your postgresql username]

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 5555
  adminConnectors:
    - type: http
      port: 5556
  requestLog:
    timeZone: UTC
    appenders:
      - type: console
#      - type: file
#        currentLogFilename: ./log/taimurain/taimurain-access.log
#        threshold: ALL
#        archive: true
#        archivedLogFilenamePattern: ./log/taimurain/taimurain-%d{yyyy-MM-dd}.log.gz
#        archivedFileCount: 7

logging:
  level: INFO
  loggers:
    com.hello.suripu.taimurain: DEBUG
    com.amazonaws: WARN
  appenders:
     - type: console
#    - type: file
#      threshold: INFO
#      currentLogFilename: /var/log/taimurain/taimurain.log
#      archivedLogFilenamePattern: /var/log/taimurain/taimurain-%d{yyyy-MM-dd}.log.gz
#      archivedFileCount: 5
#    - type: papertrail
#      host: logs2.papertrailapp.com
#      port: 11366
#      ident: taimurain
#      # timezone: UTC
#      # facility: USER
#      # sendLocalName: true

dynamodb:
  region: us-east-1
  tables:
    alarm_info : prod_alarm_info
    features : features
    firmware_upgrade_path : fw_upgrade_path
    firmware_versions : prod_firmware_versions_mapping
    ota_history : ota_history
    pill_key_store : pill_key_store
    ring_time_history: prod_ring_history_by_account
    sense_key_store : key_store
    sync_response_commands : prod_response_commands
    teams : teams
    calibration: prod_calibration
    sense_state: prod_sense_state

  endpoints:
      alarm_info : http://dynamodb.us-east-1.amazonaws.com
      features : http://dynamodb.us-east-1.amazonaws.com
      firmware_upgrade_path : http://dynamodb.us-east-1.amazonaws.com
      firmware_versions : http://dynamodb.us-east-1.amazonaws.com
      ota_history : http://dynamodb.us-east-1.amazonaws.com
      pill_key_store : http://dynamodb.us-east-1.amazonaws.com
      ring_time_history: http://dynamodb.us-east-1.amazonaws.com
      sense_key_store : http://dynamodb.us-east-1.amazonaws.com
      sync_response_commands : http://dynamodb.us-east-1.amazonaws.com
      teams : http://dynamodb.us-east-1.amazonaws.com
      calibration : http://dynamodb.us-east-1.amazonaws.com
      sense_state: http://dynamodb.us-east-1.amazonaws.com

neural_net_config:
  bucket: hello-timeline-models
  key: net.config
