metrics_enabled : false
debug: true

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello



server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 5555
  adminConnectors:
    - type: http
      port: 5556
  requestLog:
    timeZone: UTC
    appenders:
      - type: console
#      - type: file
#        currentLogFilename: ./log/taimurain/taimurain-access.log
#        threshold: ALL
#        archive: true
#        archivedLogFilenamePattern: ./log/taimurain/taimurain-%d{yyyy-MM-dd}.log.gz
#        archivedFileCount: 7

logging:
  level: INFO
  loggers:
    com.hello.suripu.taimurain: DEBUG
    com.amazonaws: WARN
  appenders:
     - type: console
#    - type: file
#      threshold: INFO
#      currentLogFilename: /var/log/taimurain/taimurain.log
#      archivedLogFilenamePattern: /var/log/taimurain/taimurain-%d{yyyy-MM-dd}.log.gz
#      archivedFileCount: 5
#    - type: papertrail
#      host: logs2.papertrailapp.com
#      port: 11366
#      ident: taimurain
#      # timezone: UTC
#      # facility: USER
#      # sendLocalName: true

neural_net_config:
  bucket: hello-timeline-models
  key: net.config
